import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from './components/index/Navbar';
import TopPaper from './components/index/TopArticle';
import BottomArticle from './components/index/BottomArticle';
import Sights from './components/index/Sights';
import Footer from './components/index/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Robonit - IWG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <TopPaper />
        <BottomArticle />
        <Sights />
        <Footer />
      </main>
    </>
  );
}
