import { useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Navbar from './components/index/Navbar';
import TopPaper from './components/index/TopArticle';
import BottomArticle from './components/index/BottomArticle';
import Sights from './components/index/Sights';
import Footer from './components/index/Footer';
import { ThemeProvider, createTheme } from '@mui/material';
import { LangContext } from './contexts';

const theme = createTheme({
  typography: {
    fontFamily: 'IRANYekanX',
  },
});

export default function Home() {
  const [lang, setLang] = useState('fa');

  return (
    <>
      <Head>
        <title>Robonit - IWG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="fa" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LangContext.Provider value={lang}>
        <ThemeProvider theme={theme}>
          <Navbar setLang={setLang} />
          <main className={styles.main}>
            <TopPaper />
            <BottomArticle />
            <Sights />
            <Footer />
          </main>
        </ThemeProvider>
      </LangContext.Provider>
    </>
  );
}
