import Head from 'next/head';
import Container from '@mui/material/Container';
import MainContent from '@/components/panel/MainContent';
import PanelNavbar from '@/components/panel/PanelNavbar';
import { ThemeProvider, createTheme } from '@mui/material';

const theme = createTheme({
  typography: {
    fontFamily: 'IRANYekanX',
  },
});

export default function Panel() {
  return (
    <>
      <Head>
        <title>پنل کاربری</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Content-Language" content="fa" />
        <link rel="icon" href="/favicon.ico" />
        <style global>{`
          body {
            background-color: #ECECEC;
          }
        `}</style>
      </Head>
      <ThemeProvider theme={theme}>
        <Container
          disableGutters
          maxWidth="xl"
          sx={{
            backgroundColor: '#ECECEC',
            direction: 'rtl',
            paddingTop: 2.5,
          }}
        >
          <PanelNavbar />
          <MainContent />
        </Container>
      </ThemeProvider>
    </>
  );
}
